### PR TITLE
fix(migration): Ignore non-renamed modules

### LINKED ISSUE #2171: Migration script includes 'Blockly' -> 'Blockly' rename, causing the script to exit early
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

@blockly/migration

### Description

Something is causing the migration script to include a rename of `Blockly` -> `Blockly`. This causes any renames after that rename to be skipped, because the loop exits early [here](https://github.com/google/blockly-samples/blob/f89bb8b69c4d4917c482d2df06131949f8c7ef71/plugins/migration/bin/rename.js#L215). So some of the renamings in the database aren't getting run.

### Reproduction steps

1. Include `Blockly.Bubble` in the manual test file.
2. Run the migration script locally (as documented in the manual test file)
3. Observe how `Blockly.Bubble` doesn't get renamed to `Blockly.bubbles.Bubble` even though it exists in the database.

### Stack trace

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by cpcallen**
## The basics

- [X] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

Fixes #2171.

### Proposed Changes

Don't create a renaming entry for modules that haven't been renamed.

Add  an entry to the test renamings that replicates the situation describe in #2171, and which causes multiple test failures without the aforementioned fix.

### Additional Information

We should _probably_ do a prefix sort on `.renamings_` (or even just sort by length descending), so that more specific entries precede less-specific ones, but after thinking quite hard about the possible consequences of this I wasn't 100% sure that this wouldn't have unforeseen consequences due to the (arguably excessive) complexity of how renamings are specified.

Since the renaming file (and therefore script) is due for a rethink anyway—since it is keyed on `goog.module` IDs that no longer actually exist in the Blockly sourcecode—I think doing the simplest possible thing for now is probably the best approach.

### CODE REVIEW

File: plugins/migration/bin/rename.js [hunk 1]
```diff
@@ -192,8 +192,11 @@ class VersionRenamer {
       //   moduleA.exportA -> moduleC.exportB
       // And we performed the module rename first, we wouldn't be able to detect
       // the export rename.
-      this.renamings_.push({old: oldModulePath, new: newModulePath});
+      if (newModulePath !== oldModulePath) {
+        this.renamings_.push({old: oldModulePath, new: newModulePath});
+      }
     }
+    console.log(this.renamings_);
```
Comment (maribethb) [inline plugins/migration/bin/rename.js]: remove log statement

**Review by maribethb — APPROVED** [review]
also needs formatting, then lgtm
