### PR TITLE
fix: caller args disconnecting shareable procedures

### LINKED ISSUE #1893: Caller inputs disconnect on reload if caller serialized above definition
**Category**

 - Plugins

**Component**

`block-shareable-procedures` `3.0.5` with Blockly `10.1.3`.

I think this did not occur with Blockly 10, but I have only verified 

**Describe the bug**

Loading a project will disconnect and bump caller inputs if it is serialized above the definition.

I think this might only affect the JSON case where the order is based on appending instead of workspace placement.

**To Reproduce**

The easiest way is to add `block-shareable-procedures` to the playground.

Steps:

```
cd plugins/dev-tools
npm install
npm add "@blockly/block-shareable-procedures"   # Also note versions above just in case
```

Activate plugin in playground:
```diff
diff --git a/plugins/dev-tools/test/index.js b/plugins/dev-tools/test/index.js
index 15c40817..2a0ea1bd 100644
--- a/plugins/dev-tools/test/index.js
+++ b/plugins/dev-tools/test/index.js
@@ -12,6 +12,17 @@
 import * as Blockly from 'blockly';
 import {createPlayground, toolboxCategories} from '../src/index';
 
+const {
+  blocks,
+  unregisterProcedureBlocks,
+  registerProcedureSerializer,
+} = require('@blockly/block-shareable-procedures');
+
+unregisterProcedureBlocks();
+Blockly.common.defineBlocks(blocks);
+
+registerProcedureSerializer();
+
 /**
  * Create a workspace.
  * @param {HTMLElement} blocklyDiv The blockly container div.
```

See video below for the reproduction steps:
- **Start** with any statement block, e.g. repeat.
- Create a procedure with some arguments.
- Add a caller to the workspace, attach it to previously mentioned statement. (JSON should now have it _above_ procedure def)
- Attach some input blocks
- Press refresh to reload
- The input block will disconnect

**Expected behavior**

Not disconnect inputs.

**Screenshots**

https://github.com/google/blockly-samples/assets/12326241/dd016a80-36ec-4af1-95ac-20a683b2ddec

### PR DESCRIPTION
**Pull request by BeksOmega**
## The basics

- [X] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

Fixes https://github.com/google/blockly-samples/issues/1893

### Proposed Changes

Adds back setting up the argsMap in updateParams.

### Reason for Changes

Before if we got any procedure model updates before we got any move events, our argsMap would be empty so all of the our blocks would get disconnected. This makes sure that we at least save the args that are currently attached to the block before doing any reconfiguration.

### Test Coverage

Tested the repro steps for https://github.com/google/blockly-samples/issues/1893 and https://github.com/google/blockly-samples/issues/1859. Neither reproduces.

Also reconfigured the test pages to make it easier to test a single workspace.

### Documentation

N/A

### Additional Information

N/A

### CODE REVIEW

File: plugins/block-shareable-procedures/src/blocks.ts [hunk 1]
```diff
@@ -1003,13 +1003,29 @@ const procedureCallerUpdateShapeMixin = {
...
     this.prevParams_ = [...this.getProcedureModel().getParameters()];
   },
 
+  /**
+   * Makes sure that if we are updating the parameters before any move events
+   * have happened, the args map records the current state of the block. Does
+   * not remove entries from the array, since blocks can be disconnected
+   * temporarily during mutation (which triggers this method).
+   */
+  ensureArgsMapIsInitialized_: function() {
```
Comment (rachel-fenichel) [inline plugins/block-shareable-procedures/src/blocks.ts]: Name suggestion: `syncArgsMap`

File: plugins/block-shareable-procedures/test/index.js [hunk 2]
```diff
@@ -22,6 +23,14 @@ let workspace1;
 let workspace2;
 
 document.addEventListener('DOMContentLoaded', function() {
+  injectTwoWorkspaces();
+  // injectOneWorkspace();
```
Comment (rachel-fenichel) [inline plugins/block-shareable-procedures/test/index.js]: Remove commented out line.
