### PR TITLE
fix: Fix TS errors in plugins/toolbox-search

### LINKED ISSUE #2029: Enable strict mode for toolbox-search
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

toolbox-search

### Problem

_No response_

### Request

The toolbox-search plugin does not have "[strict mode](https://www.typescriptlang.org/tsconfig#strict)" enabled for TypeScript. We should enable it to have better type checking for our plugins, but doing so may show some TypeScript errors that need to be fixed first.

This would be a good first issue for anyone experienced with working in TypeScript. You may need to adjust types, add checks for null or undefined, or make other fixes. If you have questions, feel free to ask here! In general, the team prefers avoiding casts and using `!` to coerce non-null types, and instead adding appropriate checks.

To work on this issue:

1. Run `npm install` at the root of Blockly samples to set up dependencies.
2. Navigate to the plugin's directory
1. Change `strict: false` to `strict: true` in the plugin's tsconfig.json
2. Run `npm run build` and see if there are any TypeScript errors.
3. Resolve any TypeScript errors, if present. If not, then we got lucky and accidentally wrote strict code! Yay!
4. Run `npm run build` again to make sure there are no TypeScript errors.
5. Run `npm run start` and play with the plugin in the playground to make sure the plugin still behaves as expected.
6. Run `npm run test` to run any automated tests.
7. Run `npm run lint` to make sure there are no formatting errors.
8. Open a PR with your changes!

### Alternatives considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elvisvoer**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

This PR fixes the TypeScript errors shown when running the `plugins/toolbox-search` using tsc `5.0.4`.

### CODE REVIEW

File: plugins/toolbox-search/test/index.ts [hunk 1]
```diff
@@ -27,7 +27,7 @@ function createWorkspace(
 }
 
 document.addEventListener('DOMContentLoaded', function () {
-  const toolbox = Object.assign({}, toolboxCategories);
+  const toolbox = Object.assign({}, toolboxCategories) as unknown as Blockly.utils.toolbox.ToolboxInfo;
```
Comment (BeksOmega) [inline plugins/toolbox-search/test/index.ts]: So it looks like the [type in the dev-tools plugin](https://github.com/google/blockly-samples/blob/6d1d5a57c78c2072f4874644a6eddca5f5764b35/plugins/dev-tools/src/index.d.ts#L112) is incorrect. Could you change `toolboxCategories` and `toolboxSimple` to both be of type `Blockly.utils.toolbox.ToolboxInfo`? Then you should be able to change this to:
```suggestion
  const toolbox = {...toolboxCategories};
```
And the types should work correctly!

File: plugins/toolbox-search/test/index.ts [hunk 2]
```diff
@@ -37,7 +37,7 @@ document.addEventListener('DOMContentLoaded', function () {
     toolbox,
   };
   createPlayground(
-    document.getElementById('root'),
+    document.getElementById('root')!,
```
Comment (BeksOmega) [inline plugins/toolbox-search/test/index.ts]: Can you change this to check if `'root'` exists instead of asserting it exists?

**Review by BeksOmega — CHANGES_REQUESTED** [review]
Thank you for your work on this! Looks like you uncovered a typing error in a different plugin too, so that's great :D

**Comment by BeksOmega** [comment]
Heya @elvisvoer Are you still interested in working on this? If not I'll close it next Friday!

**Comment by elvisvoer** [comment]
@BeksOmega yes, sorry didn't have the time to address your feedback yet. Hopefully I get a chance this weekend.

File: plugins/toolbox-search/test/index.ts (hunk 1 above)
Comment (elvisvoer) [reply plugins/toolbox-search/test/index.ts]: done!

File: plugins/toolbox-search/test/index.ts (hunk 2 above)
Comment (elvisvoer) [reply plugins/toolbox-search/test/index.ts]: done!

**Review by BeksOmega — APPROVED** [review]
This looks great thank you for the fixes!
