### PR TITLE
fix: minimap rendering issue

### LINKED ISSUE #1926: Minimap should use the renderer of the main workspace
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

workspace-minimap

### Description

The minimap does not use the renderer of the main workspace.

### Reproduction steps

1. CD into the workspace-minimap directory.
2. Run `npm run start`
3. In the right options pallet under Options > renderer switch the dropdown to "zelos".
4. Drag some blocks into the workspace.
5. Observe how the main workspace uses the Zelos renderer, but the minimap uses the Geras one.

### Additional Info

Originally reported here: https://groups.google.com/g/blockly/c/Xt8pD_ST1B0/m/40NPAV8jAwAJ

## To Fix

1) Run the reproduction steps and make sure you can reproduce the issue.
2) Modify the [minimap inject call](https://github.com/google/blockly-samples/blob/e45ad05b9f5f6cb717b8337c60df09fa0128e06b/plugins/workspace-minimap/src/minimap.ts#L64) to copy the renderer from the `primaryWorkspace`.
2) Run the reproduction steps and make sure you can't reproduce the issue.

### PR DESCRIPTION
**Pull request by thexeromin**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

Fixes #1926

### Proposed Changes

This PR modify the [minimap inject call](https://github.com/google/blockly-samples/blob/e45ad05b9f5f6cb717b8337c60df09fa0128e06b/plugins/workspace-minimap/src/minimap.ts#L64) to copy the renderer from the `primaryWorkspace`

### Reason for Changes

As discussed in the issue, if we change the renderer option from `geras` to `zelos` in the main workspace then the minimap still uses the `geras` renderer. So if we use the renderer of the main workspace in minimap then this issue will be resolved.

### Test Coverage

1. Run it using the steps mentioned in the issue.

### CODE REVIEW

File: plugins/workspace-minimap/src/minimap.ts [hunk 1]
```diff
@@ -80,6 +80,7 @@ export class Minimap {
             },
             readOnly: true,
             theme: this.primaryWorkspace.getTheme(),
+            renderer: this.primaryWorkspace.options.renderer
```
Comment (BeksOmega) [inline plugins/workspace-minimap/src/minimap.ts]:
```suggestion
            renderer: this.primaryWorkspace.options.renderer,
```

**Review by BeksOmega — CHANGES_REQUESTED** [review]
This LGTM! Just one lint fix =)

**Comment by thexeromin** [comment]
@BeksOmega I have fixed the lint.

**Comment by BeksOmega** [comment]
Sweet! Thank you for your contribution @itsfloki  :D This looks great! Let me know if you'd like to work on another issue and I can recommend some for you =)

**Comment by thexeromin** [comment]
> Sweet! Thank you for your contribution @itsfloki :D This looks great! Let me know if you'd like to work on another issue and I can recommend some for you =)

Yaa sure

**Comment by BeksOmega** [comment]
@itsfloki would you be interested in https://github.com/google/blockly-samples/issues/1922 ? If so could you comment there so I can assign you?

Best wishes,
--Beka
