### PR TITLE
fix: replace scrollToVisible_ with standard centerOnBlock

### LINKED ISSUE #1677: plugin-workspace-search use centerOnBlock for scrollToVisible_
Can we use this to move the block to the center of the workspace:
https://developers.google.com/blockly/reference/js/blockly.workspacesvg_class.centeronblock_1_method.md
For the scrollToVisible() call:
https://github.com/google/blockly-samples/blob/master/plugins/workspace-search/src/WorkspaceSearch.js#L634

### PR DESCRIPTION
**Pull request by mrkprdo**
This is an attempt to fix #1677.

### CODE REVIEW

File: plugins/workspace-search/src/WorkspaceSearch.js [hunk 1]
```diff
@@ -636,6 +636,13 @@ export class WorkspaceSearch {
       // Cannot scroll to block in a non-movable workspace.
       return;
     }
+
+    if (typeof this.workspace_.centerOnBlock === 'function') {
```
Comment (BeksOmega) [inline plugins/workspace-search/src/WorkspaceSearch.js]: Hello! Thanks for the fix :D Instead of changing `scrollToVisible` could you just delete this method and instead call `centerOnblock` in its place? `centerOnBlock` should  always be defined so no need to worry about that!

**Review by BeksOmega — CHANGES_REQUESTED** [review]

File: plugins/workspace-search/src/WorkspaceSearch.js (hunk 1 above)
Comment (mrkprdo) [reply plugins/workspace-search/src/WorkspaceSearch.js]: Ok, I will do that.

**Review by BeksOmega — APPROVED** [review]
LGTM! Thank you for the fix :D

File: plugins/workspace-search/src/WorkspaceSearch.js (hunk 1 above)
Comment (mrkprdo) [reply plugins/workspace-search/src/WorkspaceSearch.js]: Done
