### PR TITLE
removed opt_ prefix from optional parameters and gave them default value in plugins

### LINKED ISSUE #667: Rename variables that start with opt_
This is a *good first issue* for people who want to start contributing to this repository.

**Category**

Plugins

**Component**

All plugins

**Describe the bug**

The existing code uses `opt_` as a prefix for optional parameter names. This is based on old recommendations in Google's style guide.

The style guide now [says](https://google.github.io/styleguide/jsguide.html#naming-parameter-names) that parameter names should all be written in `lowerCamelCase`.

You can see all of the places where the wrong naming convention is used by running `npm run lint` from the root of the repository.

**Steps to fix**

1. Run `npm run lint` from the root of the repository.
2. Choose a file with lint errors due to camelcase issues.
3. Replace all names: `opt_someParameterName` should become `optSomeParameterName`.
4. Make a pull request.

### PR DESCRIPTION
**Pull request by lazy-geek**
fixes #667

### CODE REVIEW

**Comment by lazy-geek** [comment]
@googlebot I signed it!

**Comment by lazy-geek** [comment]
@rachel-fenichel can you review this?

**Comment by lazy-geek** [comment]
I have fixed the typo causing test to fail , can you rerun the tests?

**Comment by rachel-fenichel** [comment]
@alschmiedt is going to take over review today. I had to approve tests for the first run, but now they'll run automatically on push.

**Comment by lazy-geek** [comment]
@rachel-fenichel understood

File: plugins/block-plus-minus/src/field_minus.js [hunk 1]
```diff
@@ -13,18 +13,18 @@ import * as Blockly from 'blockly/core';
...
+ * @param {Object=} args Untyped args passed to block.minus when the field
  *     is clicked.
  * @return {Blockly.FieldImage} The minus field.
  */
-export function createMinusField(opt_args) {
+export function createMinusField(args = undefined) {
   const minus = new Blockly.FieldImage(minusImage, 15, 15, undefined, onClick_);
   /**
    * Untyped args passed to block.minus when the field is clicked.
    * @type {Object}
```
Comment (alschmiedt) [inline plugins/block-plus-minus/src/field_minus.js]: This type should be updated to be `?Object|undefined`.

The `?` denotes that the object can be null but not undefined.

`|undefined` denotes that the object can also be undefined.

All together this means that `args` can be null, undefined, or an object. 

More information on the type system we use can be found on this [page](https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System).

File: plugins/block-plus-minus/src/field_plus.js [hunk 2]
```diff
@@ -13,18 +13,18 @@ import * as Blockly from 'blockly/core';
...
+ * @param {Object=} args Untyped args passed to block.minus when the field
  *     is clicked.
  * @return {Blockly.FieldImage} The Plus field.
  */
-export function createPlusField(opt_args) {
+export function createPlusField(args = undefined) {
   const plus = new Blockly.FieldImage(plusImage, 15, 15, undefined, onClick_);
   /**
    * Untyped args passed to block.plus when the field is clicked.
    * @type {Object}
```
Comment (alschmiedt) [inline plugins/block-plus-minus/src/field_plus.js]: Update to `?Object|undefined`.

File: plugins/continuous-toolbox/src/ContinuousMetrics.js [hunk 3]
```diff
@@ -21,8 +21,8 @@ export class ContinuousMetrics extends Blockly.MetricsManager {
    * The default viewport includes the flyout.
    * @override
    */
-  getViewMetrics(opt_getWorkspaceCoordinates) {
-    const scale = opt_getWorkspaceCoordinates ? this.workspace_.scale : 1;
+  getViewMetrics(getWorkspaceCoordinates) {
```
Comment (alschmiedt) [inline plugins/continuous-toolbox/src/ContinuousMetrics.js]: Add a default value. ` = undefined`.

File: plugins/continuous-toolbox/src/ContinuousMetricsFlyout.js [hunk 4]
```diff
@@ -19,13 +19,13 @@ export class ContinuousFlyoutMetrics extends Blockly.FlyoutMetricsManager {
    * @override
    */
   getScrollMetrics(
-      opt_getWorkspaceCoordinates, opt_viewMetrics, opt_contentMetrics) {
+      getWorkspaceCoordinates = undefined, viewMetricsParam = undefined, contentMetricsParam = undefined) {
```
Comment (alschmiedt) [inline plugins/continuous-toolbox/src/ContinuousMetricsFlyout.js]: This line exceeds the max line limit of 80. Please wrap the line according to the [style guide](https://google.github.io/styleguide/jsguide.html#formatting-line-wrapping).

Comment (alschmiedt) [reply plugins/continuous-toolbox/src/ContinuousMetricsFlyout.js]: I think a more descriptive name here might be `cachedViewMetrics` and `cachedContentMetrics`.

File: plugins/field-date/src/field_date.js [hunk 5]
```diff
@@ -177,20 +177,20 @@ Blockly.FieldDate.prototype.updateEditor_ = function() {
...
- * @param {Event=} opt_e Optional mouse event that triggered the field to
+ * @param {Event=} e Optional mouse event that triggered the field to
  *     open, or undefined if triggered programmatically.
- * @param {boolean=} _opt_quietInput Quiet input.
+ * @param {boolean=} quietInput Quiet input.
  * @protected
  * @override
  */
-Blockly.FieldDate.prototype.showEditor_ = function(opt_e, _opt_quietInput) {
+Blockly.FieldDate.prototype.showEditor_ = function(e = undefined, quietInput) {
```
Comment (alschmiedt) [inline plugins/field-date/src/field_date.js]: This needs a default value and we can keep the `_` at the beginning of the word. The `_` means that the while the parameter is passed in, it is not being used in the function. This would look like`_quietInput = undefined`.

File: plugins/field-date/src/field_date.js [hunk 6]
```diff
@@ -409,16 +409,16 @@ goog.getMsgOrig = goog.getMsg;
  * Overrides the default Closure function to check for a Blockly.Msg first.
  * Used infrequently, only known case is TODAY button in date picker.
  * @param {string} str Translatable string, places holders in the form {$foo}.
- * @param {Object.<string, string>=} opt_values Maps place holder name to value.
+ * @param {Object.<string, string>=} values Maps place holder name to value.
  * @return {string} Message with placeholders filled.
  * @suppress {duplicate}
  */
-goog.getMsg = function(str, opt_values) {
+goog.getMsg = function(str, values) {
```
Comment (alschmiedt) [inline plugins/field-date/src/field_date.js]: Add a default value. `values=undefined`

File: plugins/field-slider/src/field_slider.js [hunk 7]
```diff
@@ -17,24 +17,24 @@ import * as Blockly from 'blockly/core';
...
    *    See the [field creation documentation]{@link https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/number#creation}
    *    for a list of properties this parameter supports.
    * @extends {Blockly.FieldNumber}
    * @constructor
    */
-  constructor(opt_value, opt_min, opt_max, opt_precision,
-      opt_validator, opt_config) {
-    super(opt_value, opt_min, opt_max, opt_precision, opt_validator,
-        opt_config);
+  constructor(value = 0, min = undefined, max = undefined, precision = undefined,
```
Comment (alschmiedt) [inline plugins/field-slider/src/field_slider.js]: I think we actually want `value=undefined` here. In `field.js` we [set the value of the field](https://github.com/google/blockly/blob/fc6a1be3d982349292b630d2818b3b5509688d5f/core/field.js#L67) to the `DEFAULT_VALUE`. In the case of [FieldNumber](https://github.com/google/blockly/blob/fc6a1be3d982349292b630d2818b3b5509688d5f/core/field_number.js#L83) (which this class extends) this is 0. If a user wants to change the default value of the field they can set the `DEFAULT_VALUE`. By adding this default parameter we would be overriding that other value.

File: plugins/field-slider/src/field_slider.js [hunk 8]
```diff
@@ -69,19 +69,19 @@ export class FieldSlider extends Blockly.FieldNumber {
...
-   * @param {Event=} opt_e Optional mouse event that triggered the field to
+   * @param {Event=} e Optional mouse event that triggered the field to
    *     open, or undefined if triggered programmatically.
-   * @param {boolean=} _opt_quietInput Quiet input.
+   * @param {boolean=} quietInput Quiet input.
    * @protected
    * @override
    */
-  showEditor_(opt_e, _opt_quietInput) {
+  showEditor_(e = undefined, quietInput = undefined) {
```
Comment (alschmiedt) [inline plugins/field-slider/src/field_slider.js]: Add back the `_` in front of `quietInput`.

File: plugins/fixed-edges/src/index.js [hunk 9]
```diff
@@ -72,19 +72,19 @@ export class FixedEdgesMetricsManager extends Blockly.MetricsManager {
...
+   * @param {!Blockly.MetricsManager.ContainerRegion=} viewMetricsParam The view
    *     metrics if they have been previously computed. Passing in null may
    *     cause the view metrics to be computed again, if it is needed.
    * @return {!Blockly.MetricsManager.FixedEdges} The fixed edges of the scroll
    *     area.
    * @protected
    * @override
    */
-  getComputedFixedEdges_(opt_viewMetrics) {
+  getComputedFixedEdges_(viewMetricsParam = undefined) {
```
Comment (alschmiedt) [inline plugins/fixed-edges/src/index.js]: `viewMetricsParam` -> `cachedViewMetrics`

**Review by alschmiedt — COMMENTED** [review]
Thanks for the PR!

A few of the comments have to do with our types which can be a bit tricky so definitely let me know if you have any questions or if there is anything I can clarify!

**Comment by lazy-geek** [comment]
@alschmiedt thanks for feedback , i will change my code accordingly

File: plugins/block-plus-minus/src/if.js [hunk 10]
```diff
@@ -123,22 +123,22 @@ const controlsIfMutator = {
    * Appears to remove the input at the given index. Actually shifts attached
    * blocks and then removes the input at the bottom of the block. This is to
    * make sure the inputs are always IF0, IF1, etc with no gaps.
-   * @param {number?} opt_index The index of the input to "remove", or undefined
+   * @param {number?} index The index of the input to "remove", or undefined
```
Comment (lazy-geek) [inline plugins/block-plus-minus/src/if.js]: According to google style guide `?` Should be before the type like
`?number` and not `number?` , Should i correct this?

File: plugins/fixed-edges/src/index.js [hunk 11]
```diff
@@ -72,19 +72,19 @@ export class FixedEdgesMetricsManager extends Blockly.MetricsManager {
 
   /**
    * Computes the fixed edges of the scroll area.
-   * @param {!Blockly.MetricsManager.ContainerRegion=} opt_viewMetrics The view
+   * @param {!Blockly.MetricsManager.ContainerRegion=} viewMetricsParam The view
```
Comment (lazy-geek) [inline plugins/fixed-edges/src/index.js]: This is marked as non-nullable type should i change it to `?(Blockly.MetricsManager.ContainerRegion|undefined)=` or keep it non-nullable and change it to `!(Blockly.MetricsManager.ContainerRegion|undefined)=`

**Comment by lazy-geek** [comment]
@alschmiedt can you answer my questions?

File: plugins/block-plus-minus/src/field_minus.js (hunk 1 above)
Comment (lazy-geek) [reply plugins/block-plus-minus/src/field_minus.js]: Done

File: plugins/block-plus-minus/src/field_plus.js (hunk 2 above)
Comment (lazy-geek) [reply plugins/block-plus-minus/src/field_plus.js]: Done

File: plugins/continuous-toolbox/src/ContinuousMetrics.js (hunk 3 above)
Comment (lazy-geek) [reply plugins/continuous-toolbox/src/ContinuousMetrics.js]: Done

File: plugins/continuous-toolbox/src/ContinuousMetricsFlyout.js (hunk 4 above)
Comment (lazy-geek) [reply plugins/continuous-toolbox/src/ContinuousMetricsFlyout.js]: Done

File: plugins/field-date/src/field_date.js (hunk 6 above)
Comment (lazy-geek) [reply plugins/field-date/src/field_date.js]: Done

File: plugins/field-date/src/field_date.js (hunk 5 above)
Comment (lazy-geek) [reply plugins/field-date/src/field_date.js]: Done

File: plugins/field-slider/src/field_slider.js (hunk 7 above)
Comment (lazy-geek) [reply plugins/field-slider/src/field_slider.js]: Done

File: plugins/fixed-edges/src/index.js (hunk 9 above)
Comment (lazy-geek) [reply plugins/fixed-edges/src/index.js]: Done

File: plugins/field-slider/src/field_slider.js (hunk 8 above)
Comment (lazy-geek) [reply plugins/field-slider/src/field_slider.js]: Done

**Comment by lazy-geek** [comment]
Can someone approve the workflow to run?

**Comment by rachel-fenichel** [comment]
It looks like I was wrong about workflows running automatically--I have to approve it every time on this pull request, but hopefully not on future ones. Thanks for your patience.

File: plugins/block-plus-minus/src/if.js (hunk 10 above)
Comment (alschmiedt) [reply plugins/block-plus-minus/src/if.js]: Yes, that would be great. Thanks!

Comment (lazy-geek) [reply plugins/block-plus-minus/src/if.js]: I already did that

File: plugins/fixed-edges/src/index.js (hunk 11 above)
Comment (lazy-geek) [reply plugins/fixed-edges/src/index.js]: For now i have changed it to `!(Blockly.MetricsManager.ContainerRegion|undefined)=`

Comment (alschmiedt) [reply plugins/fixed-edges/src/index.js]: For [optional parameters](https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System#optional) you do not actually need the `|undefined` since the `=` denotes that it is optional and therefore can be undefined. The `|undefined` is only needed when defining property types. More documentation on this can be found in the [Optional Parameters and Properties section](https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System#nullable-vs-optional-parameters-and-properties). When I mentioned adding `|undefined` it was just for [this line](https://github.com/google/blockly-samples/blob/e024b9e53a4d0f6d45f3e9103bf9503fb194f0eb/plugins/block-plus-minus/src/field_minus.js#L24) and [this line](https://github.com/google/blockly-samples/blob/e024b9e53a4d0f6d45f3e9103bf9503fb194f0eb/plugins/block-plus-minus/src/field_plus.js#L24) all the optional parameters can be reverted so they only have the `=` sign. Sorry for the confusion! And let me know if you have any other questions.

Comment (lazy-geek) [reply plugins/fixed-edges/src/index.js]: Oh! Sorry i thought you were talking about `@param`  line

File: plugins/block-plus-minus/src/if.js (hunk 10 above)
Comment (lazy-geek) [reply plugins/block-plus-minus/src/if.js]: @alschmiedt So, this should be `?number=` right? , Because it is also optional

Comment (alschmiedt) [reply plugins/block-plus-minus/src/if.js]: Yes. Good catch!

**Comment by lazy-geek** [comment]
@alschmiedt i have reverted unnecessary changes and only changed what was needed , can you review it? And also can you approve the workflow to run?

**Review by alschmiedt — APPROVED** [review]
Looks good to me!

Thanks for all your work on this PR!
