### PR TITLE
fix: Enables strict mode for toolbox-search

### LINKED ISSUE #2029: Enable strict mode for toolbox-search
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Component

toolbox-search

### Problem

_No response_

### Request

The toolbox-search plugin does not have "[strict mode](https://www.typescriptlang.org/tsconfig#strict)" enabled for TypeScript. We should enable it to have better type checking for our plugins, but doing so may show some TypeScript errors that need to be fixed first.

This would be a good first issue for anyone experienced with working in TypeScript. You may need to adjust types, add checks for null or undefined, or make other fixes. If you have questions, feel free to ask here! In general, the team prefers avoiding casts and using `!` to coerce non-null types, and instead adding appropriate checks.

To work on this issue:

1. Run `npm install` at the root of Blockly samples to set up dependencies.
2. Navigate to the plugin's directory
1. Change `strict: false` to `strict: true` in the plugin's tsconfig.json
2. Run `npm run build` and see if there are any TypeScript errors.
3. Resolve any TypeScript errors, if present. If not, then we got lucky and accidentally wrote strict code! Yay!
4. Run `npm run build` again to make sure there are no TypeScript errors.
5. Run `npm run start` and play with the plugin in the playground to make sure the plugin still behaves as expected.
6. Run `npm run test` to run any automated tests.
7. Run `npm run lint` to make sure there are no formatting errors.
8. Open a PR with your changes!

### Alternatives considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kapooraryan**
## The basics

- [x] I [validated my changes](https://developers.google.com/blockly/guides/contribute/samples#making_and_verifying_a_change)

### Resolves

Closes #2029 

### Proposed Changes

Enables strict mode for the toolbox-search plugin by configuring "strict":true in tsconfig.json.

Typescript errors that arose as a result:
TS_Errors

Solved by making necessary changes to the toolbox_search.ts file:
Solved_Err_TS

### Reason for Changes

Enables strict mode and carries out checks for null or possibly undefined objects.

### Additional Information

Ran npm run lint to ensure no errors! Let me know if there are any changes required.

**Note**: Was using this StackOverflow [discussion](https://stackoverflow.com/a/72404011/22548352) as reference earlier but this seems to be a forbidden non-null assertion as we are telling typescript the object exists.

### CODE REVIEW

**Comment by kapooraryan** [comment]
@BeksOmega Let me know if this is okay?

File: plugins/toolbox-search/src/toolbox_search.ts [hunk 1]
```diff
@@ -131,7 +131,7 @@ export class ToolboxSearchCategory extends Blockly.ToolboxCategory {
    */
   private initBlockSearcher() {
     const availableBlocks = new Set<string>();
-    this.workspace_.options.languageTree.contents.map((item) =>
+    this.workspace_.options.languageTree?.contents?.map((item) =>
```
Comment (BeksOmega) [inline plugins/toolbox-search/src/toolbox_search.ts]: This is unrelated, but can you switch this to `forEach` instead of `map`? We shouldn't be using `map` if we're not using the return value.

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#:~:text=Since%20map%20builds%20a%20new%20array%2C%20calling%20it%20without%20using%20the%20returned%20array%20is%20an%20anti%2Dpattern%3B%20use%20forEach%20or%20for...of%20instead.

File: plugins/toolbox-search/src/toolbox_search.ts [hunk 2]
```diff
@@ -157,19 +157,22 @@ export class ToolboxSearchCategory extends Blockly.ToolboxCategory {
...
     } else {
-      this.searchField.value = '';
-      this.searchField.blur();
+      const searchField = this.searchField
+      if(searchField){
+        searchField.value = '';
+      }
+      this.searchField?.blur();
     }
   }
```
Comment (BeksOmega) [inline plugins/toolbox-search/src/toolbox_search.ts]: I think in this case it's more readable to return early rather than using `?.` repeatedly.

```ts
super.setSelected(isSelected);
if (!this.searchField) return;
if (isSelected) {
// etc...
```

**Review by BeksOmega — COMMENTED** [review]
This looks great! Thank you for the fixes :D Two nits (one unrelated to your changes) then I'll give this a manual test, and should be good to merge!

File: plugins/toolbox-search/src/toolbox_search.ts (hunk 1 above)
Comment (kapooraryan) [reply plugins/toolbox-search/src/toolbox_search.ts]: Went through the reference you provided and updated the same.

File: plugins/toolbox-search/src/toolbox_search.ts (hunk 2 above)
Comment (kapooraryan) [reply plugins/toolbox-search/src/toolbox_search.ts]: Yes, you're right. Added the check for the object before instead of using ? repeatedly. Let me know if there's anything else @BeksOmega .

**Comment by BeksOmega** [comment]
Heya @kapooraryan, can you run the formatter (`npm run format` at root) and commit the changes? Then this should be good to go!

**Comment by kapooraryan** [comment]
> Heya @kapooraryan, can you run the formatter (`npm run format` at root) and commit the changes? Then this should be good to go!

Hey @BeksOmega , pushed the commit to this PR. Lmk if it's okay?

**Comment by BeksOmega** [comment]
> > Heya @kapooraryan, can you run the formatter (`npm run format` at root) and commit the changes? Then this should be good to go!
> 
> Hey @BeksOmega , pushed the commit to this PR. Lmk if it's okay?

Looks perfect! Thank you so much for your work on this :D
